- src/GlobalStyle.js
- src/components/PostList/Post/PostInfo/index.jsx
- src/components/PostList/Post/UserInfo/index.jsx
- src/components/PostList/Post/index.jsx
- src/components/PostList/index.jsx
- src/pages/Main/index.jsx
- src/styles/color.js
- src/styles/media.js
<br />
1. postlist UI 구현
- 반응형 구현
> Add: postlist UI 구현

- src/pages/DetailPage/index.jsx
- src/pages/MyLolog/index.jsx
<br />
1. 상세페이지, 내벨로그페이지 폴더 생성
> Add: 상세페이지, 내벨로그페이지 생성

- src/components/Setting/UserInformation/SocialInfo/index.jsx
- src/components/Setting/UserInformation/Title/index.jsx
- src/components/Setting/UserIntroduction/index.jsx
<br />
1. 소셜 정보 수정 코드 리팩토링
2. 안쓰는 state 함수 삭제
> Refactor: 소셜 정보 수정 코드 리팩토링

- src/App.jsx
- src/components/Series/index.jsx
- src/components/User/index.jsx
- src/components/UserBox/Social/index.jsx
- src/components/UserBox/User/index.jsx
- src/components/UserBox/index.jsx
- src/pages/MyLolog/index.jsx
<br />
1. 내 벨로그, 설정페이지 유저 박스 레이아웃 구현
2. 내 벨로그 라우터 지정
> Add: 내 블로그 유저 박스 레이아웃 구현 및 라우터 설정

- src/components/PostListNavBar/More/index.jsx
<br />
1. 토글 on/off하는 변수이름 fix
> Fix: more 버튼 props 변수명 fix

- src/components/Setting/UserProfile/Index.jsx
- src/components/UserBox/User/index.jsx
- src/components/UserProfileImage/index.jsx
> Refactor: 유저 프로필 이미지 컴포넌트 이동

- src/components/MyLogNavBar/index.jsx
- src/pages/MyLolog/index.jsx
<br />
1. 내 블로그 네브 바 레이아웃 구현
2. 네브 바 라우터 지정
3. 네브 바 라우터 변경 시 스타일 구현
> Add: 내 블로그 네브 바 레이아웃 및 기능 구현

- src/pages/MyLolog/Post/MaxWidth1199pxTagList/index.jsx
- src/pages/MyLolog/Post/TagList/index.jsx
- src/pages/MyLolog/Post/index.jsx
> Add: 내 롤로그 -> 글 -> 태그목록 UI및 반응형 구현

- src/components/PostSkeleton/Post/Thumbnail/index.jsx
- src/components/PostSkeleton/Post/index.jsx
<br />
1. 글 썸네일 스켈레톤 생성
- 상위 태그에 가로, 세로 적용하고 사용
> Add: 글 섬네일 스켈레톤 컴포넌트 생성

- src/App.jsx
- src/components/Join/index.jsx
- src/components/Login/index.jsx
- src/components/LoginModal/LoginForm/index.jsx
- src/components/LoginModal/index.jsx
- src/pages/Register/index.jsx
<br />
1. 회원가입 등록 폼 레이아웃 구현
2. 버튼 클릭 시 이동 기능 구현
> Add: 회원가입 폼 레이아웃 및 기능 구현

- src/components/ConfirmModal/Index.jsx
- src/layout/Header/index.jsx
- src/pages/MyLolog/Series/SeriesPost/SeriesInfo/index.jsx
- src/pages/MyLolog/Series/index.jsx
- src/pages/Saves/SavesList/index.jsx
<br />
1. 임시글, 시리즈 생성 날짜 부분 재사용 컴포넌트 사용해서 리팩토링
2. 이 외 재사용 컴포넌트 스타일 수정
> Refactor: 임시글, 시리즈 생성 날짜 부분 재사용 컴포넌트 사용해서 리팩토링

- src/components/UserBox/Social/index.jsx
- src/components/UserBox/User/index.jsx
- src/components/UserBox/index.jsx
<br />
1. 유저 박스 반응형 추가
2. 스타일 추가
3. 소셜 링크 추가
4. 이메일 보내기 기능 구현
-
> Add: 유저 박스 반응형, 소셜 링크 기능, 이메일 보내기 기능 구현

- src/api/index.jsx
> Add: api 주소 환경변수로 관리 및 axios import

- src/pages/DetailPage/CommentArea/CommentList/index.jsx
- src/pages/DetailPage/CommentArea/index.jsx
> Add: 댓글 입력 및 갯수 UI 구현

- package-lock.json
- package.json
- src/components/Toastify/index.jsx
- src/pages/Register/index.jsx
> Add: Toasify 라이브러리 설치 및 Toast 구현

- src/components/Toastify/index.jsx
- src/pages/Saves/SavesList/Saves/index.jsx
- src/pages/Saves/SavesList/index.jsx
<br />
1. 임시글리스트에서 임시글 컴포넌트 분리
2. 삭제했을 때 토스트 뜨게
3. 폰트-사이즈 수정
4. 라우터 추가
> Add: 임시글 제목과 내용 클릭 시 에디터로 이동하는 라우터 추가

- src/components/PostNavBtn/index.jsx
- src/pages/DetailPage/NextPrePost/index.jsx
- src/pages/DetailPage/index.jsx
<br />
1. 이전, 다음 포스트 버튼 반응형 구현
> Add: 이전, 다음 포스트 반응형 구현

- src/pages/Setting/Index.jsx
- src/pages/Setting/UserInfo/Email/index.jsx
- src/pages/Setting/UserInfo/EmailReceiveSetting/Toggle/index.jsx
- src/pages/Setting/UserInfo/EmailReceiveSetting/index.jsx
- src/pages/Setting/UserInfo/SocialInfo/index.jsx
- src/pages/Setting/UserInfo/Title/index.jsx
- src/pages/Setting/UserInfo/Withdrawal/index.jsx
- src/pages/Setting/UserInfo/index.jsx
- src/pages/Setting/UserIntro/index.jsx
- src/pages/Setting/UserProfile/UploadImage/index.jsx
- src/pages/Setting/UserProfile/index.jsx
- src/store/modules/user.js
> Fix: api 연동 후 기능 픽스

- src/pages/MyLolog/About/index.jsx
- src/pages/Setting/UserIntro/index.jsx
<br />
1. lolog > about GET, PATCH 연동 및 소개글 편집 기능
> Add: lolog > about GET, PATCH 연동 및 소개글 편집 기능

- src/components/Button/Index.jsx
- src/components/FollowButton/index.jsx
- src/components/UserBox/Social/index.jsx
- src/components/UserBox/User/index.jsx
<br />
1. lolog > userbox > social map함수로 리팩토링
2. 구독버튼 색상 변경, 반응형 수정
> Refactor: lolog > userbox > social map함수로 리팩토링

- src/components/UserBox/User/index.jsx
- src/pages/MyLolog/index.jsx
> Add: 내 벨로그 프로필 통신 완료

- src/pages/DetailPage/PostArea/Content/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Snbs/Like/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Snbs/Share/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Snbs/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/index.jsx
- src/pages/DetailPage/PostArea/index.jsx
- src/pages/DetailPage/index.jsx
> Add: 게시글 좋아요 / 좋아요 취소 기능 추가

- src/pages/Saves/SavesList/index.jsx
<br />
1. 임시글 데이터 없을 때 보여지는 화면 조건 픽스
> Fix: 임시글 데이터 없을 때 보여지는 화면 조건 픽스

- src/components/AuthModal/LoginForm/index.jsx
- src/layout/Header/index.jsx
<br />
1. 로그인 후 유저아이디와 프로필 이미지 로컬스토리지에 저장
2. 로그인 실패 시 토스트로 오류메세지 출력하게 끔 추가
3. 로그인 버튼 호버시 스타일 수정
> Add: 로그인 후 유저아이디와 프로필 이미지 로컬스토리지에 저장

- src/App.jsx
- src/components/AuthModal/SocialAuth/GoogleAuth/index.jsx
- src/components/AuthModal/SocialAuth/index.jsx
- src/components/AuthModal/index.jsx
- src/pages/Follow/FollowList/Followee/index 2.jsx
- src/pages/Follow/FollowList/index 2.jsx
- src/pages/Follow/index 2.jsx
- src/pages/Register/EmailForm/index.jsx
- src/pages/Register/GoogleForm/index.jsx
- src/pages/Register/index.jsx
- src/pages/Saves/SavesList/Saves/index.jsx
- src/store/modules/mylologpostlist 2.js
- src/store/modules/seriespostlist 2.js
<br />
1. 구글 회원가입 폼 레이아웃 구현
2. 이메일 회원가입 폼과 구글 회원가입 폼 컴포넌트 분리
> Add: 구글 회원가입 폼 레이아웃 구현 및 회원가입 폼 컴포넌트 분리

- src/components/UserBox/Social/index.jsx
- src/components/UserBox/User/index.jsx
- src/components/UserBox/index.jsx
- src/pages/MyLolog/index.jsx
- src/pages/SeriesPostList/index.jsx
<br />
1. 내 정보가 아닐 때만 팔로우 버튼 보이게 구현
2. 유저 박스 유저 소셜 정보 받아오기
> Add: 내 정보가 아닐 때만 팔로우 버튼 보이게 구현 

- src/components/PostViewer/index.jsx
- src/pages/DetailPage/PostArea/Content/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Authority/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Information/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Series/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Snbs/Like/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Snbs/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/index.jsx
- src/pages/DetailPage/PostArea/index.jsx
- src/pages/DetailPage/index.jsx
- src/pages/Write/Editor/EditorFooter/index.jsx
- src/pages/Write/Editor/Tags/index.jsx
- src/pages/Write/Editor/ToolBar/index.jsx
- src/pages/Write/Editor/WriteZone/index.jsx
- src/pages/Write/Editor/index.jsx
- src/pages/Write/ReversePositionBtn/index.jsx
- src/pages/Write/UploadModal/ SettingPublic/index.jsx
- src/pages/Write/UploadModal/ModalBtns/index.jsx
- src/pages/Write/UploadModal/SettingDescription/index.jsx
- src/pages/Write/UploadModal/SettingSeries/After/index.jsx
- src/pages/Write/UploadModal/SettingSeries/index.jsx
- src/pages/Write/UploadModal/index.jsx
- src/pages/Write/index.jsx
- src/store/modules/write.js
- src/styles/media.js
> Add: 게시글 작성 페이지 기능 완성, 게시글 수정 / 삭제 기능 및 게시글 상세 페이지 반응형 레이아웃 구현

- src/components/UserBox/User/index.jsx
- src/components/UserBox/index.jsx
- src/pages/Follow/FollowList/Followee/index.jsx
- src/pages/Follow/FollowList/NoFollowee/index.jsx
- src/pages/Follow/FollowList/index.jsx
- src/pages/MyLolog/index.jsx
- src/pages/SeriesPostList/index.jsx
- src/pages/Setting/Index.jsx
- src/pages/Setting/UserInfo/Withdrawal/index.jsx
<br />
1. 팔로우 리스트 코드 리팩토링 팔로이 없을 때 화면 추가
> Refactor: 팔로우 리스트 코드 리팩토링 팔로이 없을 때 화면 추가

- src/App.jsx
- src/GlobalStyle.js
- src/components/PostList/Post/UserInfo/index.jsx
- src/components/PostList/index.jsx
- src/components/PostListNavBar/index.jsx
- src/components/UserProfileImage/index.jsx
- src/layout/Header/RightIcons/ThemeMode/index.jsx
- src/layout/Header/RightIcons/ToggleMenuList/index.jsx
- src/layout/Header/RightIcons/index.jsx
- src/layout/Header/index.jsx
- src/pages/DetailPage/PostArea/index.jsx
- src/pages/Write/Editor/EditorFooter/index.jsx
- src/pages/Write/ReversePositionBtn/index.jsx
- src/pages/Write/index.jsx
- src/styles/media.js
> Fix: 헤더 스크롤 이벤트 추가 및 반응형 구현, 게시글 작성 페이지 반응형 구현

- src/components/LikeBtn/index.jsx
- src/components/PostListNavBar/More/index.jsx
- src/layout/Header/RightIcons/index.jsx
- src/layout/Header/index.jsx
- src/pages/DetailPage/PostArea/Content/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Authority/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Information/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Series/PreNext/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Series/RouterList/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Series/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Snbs/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/Tags/index.jsx
- src/pages/DetailPage/PostArea/PostHeader/index.jsx
- src/pages/DetailPage/PostArea/index.jsx
- src/pages/DetailPage/index.jsx
- src/pages/MyLolog/MyLologPosts/index.jsx
- src/pages/MyLolog/index.jsx
- src/pages/Write/Editor/EditorFooter/index.jsx
- src/pages/Write/Editor/index.jsx
- src/pages/Write/UploadModal/SettingSeries/Setting/Create/index.jsx
- src/pages/Write/UploadModal/SettingThumbnail/index.jsx
- src/pages/Write/UploadModal/index.jsx
- src/store/modules/detailpage.js
- src/styles/media.js
> Fix: 좋아요 기능, 헤더 스크롤 이벤트, 게시글 상세페이지 초기화, 내 밸로그 검색창 위치, 업로드 모달 썸네일 및 자동 저장 수정

- src/components/ScrollTop/index.js
- src/layout/Header/index.jsx
- src/main.jsx
> Add: 페이지 이동시 스크롤 맨위로 세팅

- vite.config.js
<br />
npm run dev 했을 때 서버 바로 켜지게 추가 해보았습니다.
> add: 서버 오픈 true로

- src/layout/Header/index.jsx
<br />
1. 렌더링 전 return 해서 발생한 오류 수정
- 새 글 작성 부분은 헤더가 보이지 않도록 조건부 함수를 넣어줌.
- Header jsx 가 리턴되기전에 return null 해주니 Header 컴포넌트가 아예 렌더링되지 않아서 에러가 발생함.
- return 부분에서 조건부를 걸어주어 오류 해결
> Fix: 렌더링 전 return 해서 발생한 오류 수정

- src/layout/Header/index.jsx
<br />
1. import 문 수정
2. 헤더 렌더링 오류 수정
- 새 글 작성 페이지에는 헤더가 보이지 않도록 조건부 렌더링 구현
- 헤더 jsx가 리턴되기 전에 return null 해주니 Header 컴포넌트가 아예 렌더링되지 않아서 에러 발생
- return 부분에서 조건부 함수를 작성하여 오류 해결
> Fix: import 문 수정 및 헤더 렌더링 오류 수정

- src/pages/MyLolog/Series/SeriesCard/SeriesInfo/index.jsx
- src/pages/MyLolog/Series/SeriesCard/index.jsx
- src/pages/MyLolog/Series/index.jsx
- src/pages/SeriesPostList/PostList/index.jsx
<br />
1. 시리즈 데이터 안받아지는 것을 받아오기 위해 수정했습니다.
-
> refactor: 시리즈 정보 수정

- src/App.jsx
- src/components/AuthModal/LoginForm/index.jsx
- src/components/AuthModal/SocialAuth/GoogleAuth/index.jsx
- src/components/AuthModal/SocialAuth/OAuth.js
- src/components/AuthModal/SocialAuth/index.jsx
- src/components/UserBox/User/index.jsx
> Add: 구글 로그인/회원가입 드디어 성공 😭

- .gitignore
- src/components/Comment/CommentContent.jsx
- src/components/Comment/Textarea.jsx
- src/components/PostList/index.jsx
- src/components/PostListNavBar/More/index.jsx
- src/components/PostNavBtn/index.jsx
- src/hooks/usePostAxios.js
- src/pages/DetailPage/CommentArea/index.jsx
- src/pages/DetailPage/NextPrePost/index.jsx
- src/pages/DetailPage/index.jsx
- src/pages/MyLolog/MyLologPosts/MaxWidth1199pxTagList/index.jsx
- src/pages/MyLolog/MyLologPosts/MinWidth1200pxTagList/index.jsx
- src/pages/MyLolog/MyLologPosts/index.jsx
- src/store/modules/detailpage.js
<br />
1. 댓글 작성시 댓글 갯수 업데이트 오류
- 댓글 갯수만 관리하는 state를 만들어 댓글 작성 및 삭제시 댓글 정보를 받아와 다시 렌더링 해주게끔 수정
2. 상세 페이지 이전, 이후 포스트 css 수정
- 제목 길어질 때 나타나는 찌그러짐 수정
> Fix: 상세페이지 댓글 업데이트 오류 수정

- src/components/AuthModal/SocialAuth/index.jsx
- src/pages/Write/Editor/WriteZone/index.jsx
- src/pages/Write/UploadModal/SettingThumbnail/index.jsx
<br />
1. 게시글 작성 페이지 & 게시글 업로드 모달 썸네일 미리보기 url 수정
> Fix: thumbnail url 수정

- src/components/AuthModal/SocialAuth/index.jsx
- src/pages/Write/Editor/WriteZone/index.jsx
- src/pages/Write/UploadModal/SettingThumbnail/index.jsx
<br />
1. 게시글 작성 페이지 & 게시글 업로드 모달 썸네일 미리보기 url 수정
- 기존에 서버에서 받아오던 url 이 수정되어 미리보기 url 도 수정해줌
- 서버의 주소가 바뀌어도 파일만 있으면 유동적으로 인식되도록 할 수 있도록 수정함
> Fix: thumbnail url 수정 (#137)

- src/pages/Write/UploadModal/ModalBtns/index.jsx
- src/pages/Write/UploadModal/SettingThumbnail/index.jsx
<br />
1. thumbnail 미리보기 url 수정
> Fix: thumbnail 미리보기 url 수정 (#140)

- .gitignore
- src/components/AuthModal/SignUpForm/index.jsx
- src/components/AuthModal/SocialAuth/GoogleAuth/index.jsx
- src/components/Button/Index.jsx
- src/components/Button/index.jsx
- src/components/ConfirmModal/Index.jsx
- src/components/ConfirmModal/index.jsx
- src/components/EditButton/Index.jsx
- src/components/EditButton/index.jsx
- src/pages/Register/GoogleForm/index.jsx
- src/pages/Register/index.jsx
- src/pages/Saves/Index.jsx
- src/pages/Saves/index.jsx
- src/pages/Setting/Index.jsx
- src/pages/Setting/index.jsx
- src/store/modules/auth.js
> Revert "Add: 구글 회원가입 기능 구현"

- src/components/PostNavBtn/index.jsx
> Fix: 상세페이지 이전 다음 포스트 css 깨지는 현상 수정

- src/components/AuthModal/SocialAuth/index.jsx
- src/components/PostListNavBar/PeriodFilter/index.jsx
> Fix: 메인 내브바 기본 옵션 이번 주에서 올해로 변경

- src/components/PostListNavBar/index.jsx
- src/pages/Main/index.jsx
> Fix: 사용 하지 않는 코드 삭제 및 navbar 초기 설정 변경
